services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    networks:
      - identinet
    environment:
      - FLASK_ENV=development

  dnmonster:
    image: amouat/dnmonster:1.0
    ports:
      - "8000:8080"
    networks:
      - identinet

  redis:
    image: redis
    networks:
      - identinet

networks:
  identinet:
    driver: bridge