services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    networks:
      - identinet
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  dnmonster:
    image: amouat/dnmonster:1.0
    ports:
      - "8000:8080"
    networks:
      - identinet
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"
    networks:
      - identinet

networks:
  identinet:
    driver: bridge