services:
  web:
    image: nginx
    ports:
      - "${HOST_PORT:-8080}:80"
    container_name: container_nginx
    environment:
      NGINX_PORT: 80

  database:
    image: postgres
    container_name: container_db
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    command: ["echo", "$POSTGRES_DB $POSTGRES_USER $POSTGRES_PASSWORD"]